### ISSUE TITLE
Last character 's' is missing

### ISSUE THREAD

**Issue by MaartenSwBase** [jasperes/bash-yaml#10]
```
test_yamls:
  -
    key: app
    file: test-app.yaml
    description: Front end code
  -
    key: tasks
    file: test-long-tasks.yaml
    description: Backend end code
```
After being parsed
`test_yamls__key[1]` holds the value `task` instead of `tasks`
