### ISSUE TITLE
Iterate over result

### ISSUE THREAD

**Issue by xianghongai** [jasperes/bash-yaml#21]
```yaml
env:
  dev:
    enable: true
    host: 127.0.0.1
    port: 7090
  pro:
    enable: false
    host: 192.168.1.126
    port: 1090    
```
