### ISSUE TITLE
get sub vars from array

### ISSUE THREAD

**Issue by DimaMinka** [jasperes/bash-yaml#26]
# Description
Im use some array of packages in yml, and when im try to get in loop the sub vars of the array var im get only once the last one in first loop.

# Yaml file to test
```yml
packages:
  - name: name of package
    package: type
      ver: 1.0
      zip: http://com.zip
  - name: name of package2
    package: type2
      ver: 1.2
      zip: http://com2.zip
```

# Operation Sistem
- [x] Linux

# Bash version
```shell
4.4.20(1)-release
```
