### ISSUE TITLE
Doesn't allow to have double quotes in comments

### ISSUE THREAD

**Issue by chekalsky** [jasperes/bash-yaml#28]
# Description
If there is a double quote in comment then whole string is included as the value

# Yaml file to test
```yaml
--
name: test
process:
  name: 4K #this "comment" will be included in variable
```

# Operation Sistem
- [ ] Linux
- [x] OSX
- [ ] BSD

# Bash version
bash 3.2
