### ISSUE TITLE
Parsing Sequence of Mappings

### ISSUE THREAD

**Issue by spencer-hivert** [jasperes/bash-yaml#29]
# Description
When parsing a sequence of mappings, the parser is unable to create variables from keys that are not indented at the same level as the first key.

```
sample:
  - item-one:
    name: item-one-name
    
  - item-two:
      name: item-one-name
```

While both `item-one` and `item-two` are considered to be valid yaml, this parser is only able to parse the first variation, and `${sample__name[1]}` is empty.

```
echo "Item 1: ${sample__name[0]}"
Item 1: item-one-name

echo "Item 2: ${sample__name[1]}"
Item 2:
```

# Operation System
* [ ]  Linux
* [x]  OSX
* [ ]  BSD

# Bash version
`GNU bash, version 3.2.57(1)-release`

**Comment by kriansa** [comment]
@spencer-hivert-ck You're correct that both items are correct by YAML spec, however they mean different things. The first item in the list is an object with two properties, whilst the second one is a nested object.

For instance, you could do this:

```yaml
sample:
  - item-one: Adding-Value-Here
    name: item-one-name
    
  - item-two:
      name: item-one-name
```

But you can NOT do that:

```yaml
sample:
  - item-one:
    name: item-one-name
    
  - item-two: INVALID!
      name: item-one-name
```

Bash-yaml is able to parse your example just fine, but you should be using `sample___name[0]` to retrieve the value in the second item.
