### ISSUE TITLE
Doesn't parse text with dollar signs

### ISSUE THREAD

**Issue by djhocking** [jasperes/bash-yaml#31]
# Description
Thanks for this great function! I'm new to Bash so am not in a place to tweak the code. I was using this to import yaml text that unfortunately includes a $. This is clearly an issue for bash but I was hoping there was an adjustment to add \$ or something to the regex to allow this text to come in as a variable. For example:

```
settings:
  user:  'myname'
  pwd:  'pa$$word$20' # not real password of course
```

If I run `create_variables config.yml` then `echo $settings_pwd` it results in `'pa22336word0'`.

# Yaml file to test

```
default:
  driver: 'driver_name' 
  server: 'R$word$10'
  dsn: 'abcd'
  uid: 'GRP19$name!01'
  pwd: 'pa$$word$20'  
  port: 1234
  database: 'db.name'
```

# Operation System
[] Linux
[] OSX
[] BSD
[X] Windows 10

# Bash version

GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
--
